FROM golang:1.25 AS builder
WORKDIR /workspace
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o modelsrv-web-ui-server ./cmd/modelsrv-web-ui-server

FROM alpine:3.22
COPY --from=builder /workspace/modelsrv-web-ui-server /
COPY --from=builder /workspace/static /static
ENTRYPOINT ["/modelsrv-web-ui-server", "--static-dir", "/static"]
